# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAppraiserUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('idextuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.Extappraisers')),
            ],
        ),
    ]
