# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0002_externalappraiseruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='externalappraiseruser',
            name='idextuser',
            field=models.IntegerField(),
        ),
    ]
