# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0003_auto_20160512_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraAttributesAppraiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=200)),
                ('weightage', models.IntegerField(blank=True, null=True)),
                ('appraiser_rating', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appraisal.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraTaskAppraisers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('descritpion', models.CharField(max_length=20000)),
                ('appraiser_rating', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appraisal.Employee')),
            ],
        ),
    ]
