# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0004_extraattributesappraiser_extrataskappraisers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrataskappraisers',
            old_name='descritpion',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='extraattributesappraiser',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='extrataskappraisers',
            name='employee',
        ),
        migrations.AddField(
            model_name='extraattributesappraiser',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extraattributesappraiser',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extrataskappraisers',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extrataskappraisers',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
